plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    alias(libs.plugins.kotlinKapt)
}

def compileSdkVersion = libs.versions.compileSdk.get().toInteger()
def minSdkVersion = libs.versions.minSdk.get().toInteger()
def targetSdkVersion = libs.versions.targetSdk.get().toInteger()
def appVersionCode = libs.versions.appVersionCode.get().toInteger()
def appVersionName = libs.versions.appVersionName.get()

android {
    namespace 'com.example.mvvmcleanarchitecture'
    compileSdk compileSdkVersion

    defaultConfig {
        applicationId "com.example.mvvmcleanarchitecture"
        minSdk minSdkVersion
        targetSdk targetSdkVersion
        versionCode appVersionCode
        versionName appVersionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "TMDB_API_KEY", "\"a2b2c4bb310ebd363e399eb3d6dc5f7a\""
        buildConfigField "String", "BASE_URL", "\"https://api.themoviedb.org/3/\""

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
    buildFeatures {
        buildConfig = true
        dataBinding = true
    }
}

dependencies {
    implementation libs.androidxCoreKtx
    implementation libs.androidxAppcompat
    implementation libs.googleMaterial
    implementation libs.androidxConstraintlayout
    implementation libs.androidxActivityKtx
    testImplementation libs.junit4
    androidTestImplementation libs.androidxTestExtJunit
    androidTestImplementation libs.androidxTestEspressoCore

    implementation libs.kotlinxCoroutinesCore
    implementation libs.kotlinxCoroutinesAndroid

    // lifecycle scope
    implementation libs.androidxLifecycleRuntimeKtx
    // view model scope
    implementation libs.androidxLifecycleViewmodelKtx
    // Live data
    implementation libs.androidxLifecycleLivedataKtx
    // Saved state module for ViewModel
    implementation libs.androidxLifecycleViewmodelSavedstate

    // Room
    implementation libs.androidxRoomRuntime
    implementation libs.androidxRoomKtx
    kapt libs.androidxRoomCompiler

    // dagger
    implementation libs.daggerCore
    kapt libs.daggerCompiler
    kapt libs.daggerAndroidProcessor
    implementation libs.daggerAndroidSupport

    // retrofit
    implementation libs.retrofitCore
    implementation libs.retrofitConverterGson
    implementation libs.okhttpLoggingInterceptor

    /* Glide */
    implementation libs.glideCore
    kapt libs.glideCompiler
}
